spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/git/study/h2/jpashop-in-action
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug